[18.0][MIG] hr_holidays_public: Migration to 18.0
xaviedoanhduy/hr-holidays pull request #6
Opened 2024-10-01 05:33 UTC by xaviedoanhduy

2024-10-01 11:09 UTC, chaule97 reviewed
Update `CREDITS.md`: "The migration of this module from 17.0 to 18.0 was financially supported by Camptocamp."

2024-10-01 11:09 UTC, chaule97 commented on hr_holidays_public/__manifest__.py
> +    "version": "18.0.1.0.3",
`"version": "18.0.1.0.0",`

2024-10-01 11:13 UTC, xaviedoanhduy commented on hr_holidays_public/__manifest__.py
> +    "version": "18.0.1.0.3",
thank @chaule97, It has been updated

2024-10-01 11:25 UTC, chaule97 approved these changes
Pre-approve: Update CREDITS.md: "The migration of this module from 17.0 to 18.0 was financially supported by Camptocamp."

2024-10-02 03:34 UTC, nilshamerlinck commented
where are commits from https://github.com/xaviedoanhduy/hr-holidays/pull/5 ?

2024-10-02 08:06 UTC, xaviedoanhduy commented
> where are commits from #5 ?

Hello @nilshamerlinck, I have updated the PR

2024-10-02 09:22 UTC, nilshamerlinck commented
did you squash commits already? `https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests`

2024-10-02 09:29 UTC, xaviedoanhduy commented
> did you squash commits already? `https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests`

Done. Can you check it agian? 
cc @nilshamerlinck

2024-10-02 11:00 UTC, thienvh332 reviewed
Why don't you port this [commit](https://github.com/OCA/hr-holidays/commit/fe15e2c661f1a0f05fdb3fc521deddf2d7b03da3)?

2024-10-02 11:07 UTC, xaviedoanhduy commented
> Why don't you port this [commit](https://github.com/OCA/hr-holidays/commit/fe15e2c661f1a0f05fdb3fc521deddf2d7b03da3)?

I only port commits that don't cause conflicts. Otherwise, if conflicts arise, I blacklist them.

2024-10-02 11:16 UTC, thienvh332 reviewed
- Why don't you port this [commit](https://github.com/OCA/hr-holidays/commit/13f2713aa558cf54b582492d6c0358aecdec8a84)?

2024-10-02 11:47 UTC, nilshamerlinck commented
> I only port commits that don't cause conflicts. Otherwise, if conflicts arise, I blacklist them.

sorry, it's probably because of my unclear guidance: what I meant is that numerous conflicts can be the signal that the missing PR doesn't need to merged because it was already taken into account in another PR, e.g. a migration PR
but if there are some conflicts but the feature is interesting, you can try to adapt the code to keep the feature

2024-10-02 11:59 UTC, thienvh332 commented on hr_holidays_public/models/hr_holidays_public.py
> +        "Calendar Year", required=True, default=fields.Date.context_today
`fields.Date.context_today == default=date.today().year`?

2024-10-02 11:59 UTC, thienvh332 commented on hr_holidays_public/models/hr_holidays_public.py
> +        "Calendar Year", required=True, default=fields.Date.context_today
`fields.Date.context_today` will return a `datetime.date` type. Not an `integer` type
![image](https://github.com/user-attachments/assets/a11c7a78-19ec-4131-b315-ff6d91325658)

2024-10-03 09:11 UTC, xaviedoanhduy commented
hi @thienvh332, missed commits were added manually

2024-10-03 09:32 UTC, thienvh332 requested changes

2024-10-03 09:32 UTC, thienvh332 commented on hr_holidays_summary_email/data/mail_template_data.xml
> +</odoo>
Remove it

2024-10-03 09:36 UTC, xaviedoanhduy commented on hr_holidays_summary_email/data/mail_template_data.xml
> +</odoo>
nice catch, thank you @thienvh332 :)

2024-10-03 09:54 UTC, thienvh332 approved these changes
LGTM

2024-10-14 09:03 UTC, closed without merging